SELECT
	A.IDACORDO,
	F.IDLAN,
	FL.STATUSCOBRANEXT AS CODSTATUSCOBRANCA,
	AR.CLASSIFICACAO AS IDCLASSIFICACAO,
	IIF(AR.CLASSIFICACAO = 1, 'Origem', 'Gerado por Acordo') AS CLASSIFICACAO,
	GC.CODCCUSTO AS CODCENTROCUSTO,
	GC.NOME AS CENTROCUSTO,
	CASE  
        WHEN P.CODPERLET LIKE 'E%' THEN 'Colégio'
        WHEN P.CODPERLET LIKE '%/_%' THEN 'Graduação'
        WHEN P.CODPERLET LIKE '%EAD' THEN 'EAD' 
        ELSE 'Pós-Graduação'  
    END AS SEGMENTO,
	F.STATUSLAN AS CODSTATUSLAN,
	CASE F.STATUSLAN
		WHEN 0 THEN 'Em Aberto'
		WHEN 1 THEN 'Baixado'
		WHEN 2 THEN 'Cancelado'
		WHEN 3 THEN 'Baixado por Acordo'
		WHEN 4 THEN 'Baixado parcialmente'
		WHEN 5 THEN 'Borderô'
	END AS STATUSLAN,
	FB2.CODTB2FLX AS CODEVENTOFINANCEIRO,
	FB2.DESCRICAO AS EVENTOFINANCEIRO,
	FB3.CODTB3FLX AS CODTIPOMOVIMENTACAO,
	FB3.DESCRICAO AS TIPOMOVIMENTACAO,
	SS.CODSERVICO,
	SS.NOME AS SERVICO,
	C.CODCURSO,
	C.NOME AS CURSO,
	CASE
		WHEN C.CURPRESDIST IS NULL OR C.CURPRESDIST = 'P' THEN 'Presencial'
		WHEN C.CURPRESDIST = 'D' THEN 'À Distância'
	END MODALIDADE_CURSO,
	AL.RA,
	PP.NOME AS ALUNO,
	PP.CPF AS CPF_ALUNO,
	PP.CIDADE,
	PP.ESTADO,
	PP.ESTADOCIVIL,
	TRY_CAST(PP.DTNASCIMENTO AS DATE) AS DTNASCIMENTO,
	CFO.CODCFO AS CODRESPONSAVEL,
	CFO.NOME AS RESPONSAVEL,
	REPLACE(REPLACE(CFO.CGCCFO, '.', ''), '-', '') AS CPF_RESPONSAVEL,
	IIF(REPLACE(REPLACE(CFO.CGCCFO, '.', ''), '-', '') = PP.CPF, 'Sim', 'Não') AS ALUNO_RESPONSAVEL,
	P.CODPERLET,
	PL.PERIODO,
	TRY_CAST(F.DATAVENCIMENTO AS DATE) AS DATAVENCIMENTO,
	TRY_CAST(F.DATABAIXA AS DATE) AS DATABAIXA,
	CASE
		WHEN F.DATABAIXA IS NULL THEN DATEDIFF(DAY, F.DATAVENCIMENTO, GETDATE())
		ELSE DATEDIFF(DAY, F.DATAVENCIMENTO, F.DATABAIXA)
	END AS DIF_DIAS,
	CASE
		WHEN F.DATABAIXA IS NULL AND DATEDIFF(DAY, F.DATAVENCIMENTO, GETDATE()) > 5 THEN 1
		ELSE 0
	END AS INADIMPLENCIA,
	CASE
		WHEN F.DATABAIXA IS NULL AND DATEDIFF(DAY, F.DATAVENCIMENTO, GETDATE()) > 0 THEN 1
		WHEN F.DATABAIXA IS NOT NULL AND DATEDIFF(DAY, F.DATAVENCIMENTO, F.DATABAIXA) < 0 THEN 2
		WHEN F.DATABAIXA IS NOT NULL AND DATEDIFF(DAY, F.DATAVENCIMENTO, F.DATABAIXA) BETWEEN 0 AND 4 THEN 3
		WHEN F.DATABAIXA IS NOT NULL AND DATEDIFF(DAY, F.DATAVENCIMENTO, F.DATABAIXA) BETWEEN 5 AND 30 THEN 4
		WHEN F.DATABAIXA IS NOT NULL AND DATEDIFF(DAY, F.DATAVENCIMENTO, F.DATABAIXA) > 30 THEN 5
		WHEN F.DATABAIXA IS NULL AND DATEDIFF(DAY, F.DATAVENCIMENTO, GETDATE()) < 0 THEN 6
		ELSE 0
	END AS TIPO_PAGAMENTO,
	TRY_CAST(F.VALORORIGINAL AS DECIMAL(10, 2)) AS VALORORIGINAL, 
	TRY_CAST(F.VALORORIGINAL - F.VALOROP2 - F.VALOROP8 + ISNULL(SB.VALOR, 0) AS DECIMAL(10, 2)) AS VALORCOBRANCA,  
	TRY_CAST(F.VALORBAIXADO AS DECIMAL(10, 2)) AS VALORBAIXADO,  
	--CASE  
	--	WHEN FB.IDLAN IS NOT NULL THEN TRY_CAST(FB.VALORORIGINAL - FB.VALOROP3 - FB.VALOROP4 - FB.VALOROP8 AS DECIMAL(10, 2))
	--	ELSE TRY_CAST(F.VALORORIGINAL - F.VALOROP2 - F.VALOROP8 AS DECIMAL(10, 2))
	--END AS VALORLIQUIDO
	DBO.VALORLIQUIDO(F.IDLAN)VALORLIQUIDO
FROM
	FACORDO A (NOLOCK)
	JOIN FACORDOREL AR (NOLOCK)
		ON AR.CODCOLIGADA = A.CODCOLIGADA
		AND AR.IDACORDO = A.IDACORDO
	JOIN FLAN F (NOLOCK)
		ON F.CODCOLIGADA = AR.CODCOLIGADA
		AND F.IDLAN = AR.IDLAN
	LEFT JOIN FLANCOMPL FL (NOLOCK)
		ON FL.CODCOLIGADA = F.CODCOLIGADA AND FL.IDLAN = F.IDLAN
	LEFT JOIN GCCUSTO GC (NOLOCK)
		ON GC.CODCOLIGADA = F.CODCOLIGADA
		AND GC.CODCCUSTO = F.CODCCUSTO
	/* VALOR LÍQUIDO */
	LEFT JOIN FLANBAIXA FB (NOLOCK)  
		ON FB.CODCOLIGADA = F.CODCOLIGADA
		AND FB.IDLAN = F.IDLAN
	/* VALOR LÍQUIDO */
	LEFT JOIN SBOLSALAN SB (NOLOCK)
        ON SB.CODCOLIGADA = F.CODCOLIGADA
		AND SB.IDLAN = F.IDLAN  
        AND SB.CODBOLSA = '136'
	JOIN FTB2 FB2 (NOLOCK)
		ON FB2.CODCOLIGADA = F.CODCOLIGADA
		AND FB2.CODTB2FLX = F.CODTB2FLX
	LEFT JOIN FTB3 FB3 (NOLOCK)
		ON FB3.CODCOLIGADA = F.CODCOLIGADA
		AND FB3.CODTB3FLX = F.CODTB3FLX
	LEFT JOIN SLAN L (NOLOCK)
		ON L.CODCOLIGADA = F.CODCOLIGADA 
		AND L.IDLAN = F.IDLAN
	LEFT JOIN SPARCELA PA (NOLOCK)
		ON PA.CODCOLIGADA = L.CODCOLIGADA 
		AND PA.IDPARCELA = L.IDPARCELA
	LEFT JOIN SSERVICO SS (NOLOCK)  
		ON SS.CODCOLIGADA = PA.CODCOLIGADA  
		AND SS.CODSERVICO = PA.CODSERVICO  
	LEFT JOIN SCONTRATO CT (NOLOCK)
		ON CT.CODCOLIGADA = PA.CODCOLIGADA 
		AND CT.CODCONTRATO = PA.CODCONTRATO
	LEFT JOIN SPLETIVO P (NOLOCK)
		ON P.CODCOLIGADA = CT.CODCOLIGADA 
		AND P.IDPERLET = CT.IDPERLET
	LEFT JOIN SMATRICPL PL (NOLOCK)
		ON PL.CODCOLIGADA = CT.CODCOLIGADA 
		AND PL.IDHABILITACAOFILIAL = CT.IDHABILITACAOFILIAL
		AND PL.IDPERLET = CT.IDPERLET 
		AND PL.RA = CT.RA 
	LEFT JOIN SHABILITACAOALUNO HA (NOLOCK)
		ON HA.CODCOLIGADA = PL.CODCOLIGADA
		AND HA.IDHABILITACAOFILIAL = PL.IDHABILITACAOFILIAL
		AND HA.RA = PL.RA
	LEFT JOIN SHABILITACAOFILIAL HF (NOLOCK)
		ON HF.CODCOLIGADA = HA.CODCOLIGADA
		AND HF.IDHABILITACAOFILIAL = HA.IDHABILITACAOFILIAL
	LEFT JOIN FCFO CFO (NOLOCK)
		ON CFO.CODCOLIGADA = A.CODCOLIGADA
		AND CFO.CODCFO = A.CODCFO
	LEFT JOIN SALUNO AL (NOLOCK)
		ON AL.CODCOLIGADA = HA.CODCOLIGADA
		AND AL.RA = HA.RA
	LEFT JOIN PPESSOA PP (NOLOCK)
		ON PP.CODIGO = AL.CODPESSOA
	LEFT JOIN SCURSO C (NOLOCK)
		ON C.CODCOLIGADA = HF.CODCOLIGADA
		AND C.CODCURSO = HF.CODCURSO	
WHERE 
	A.CODCOLIGADA = 1 
